### ISSUE TITLE
yarn dev not work

### ISSUE THREAD

**Issue by Marchccc** [jellydn/nft-app#252]
jun@zhangjunshengdeMacBook-Pro nft-app % yarn dev
yarn run v1.22.4
warning ../../package.json: No license field
$ vite
Pre-bundling dependencies:
  react
  react-dom
  @web3-react/core
  ethers
  react-hot-toast
  (...and 9 more)
(this will be run only when your dependencies or config have changed)

  vite v2.7.3 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 1094ms.

 ERROR(TypeScript)  Subsequent variable declarations must have the same type.  Variable 'beforeEach' must be of type 'HookFunction', but here has type 'Lifecycle'.
 FILE  /Users/jun/node_modules/@types/jest/index.d.ts:35:13

    33 |
    34 | declare var beforeAll: jest.Lifecycle;
  > 35 | declare var beforeEach: jest.Lifecycle;
       |             ^^^^^^^^^^
    36 | declare var afterAll: jest.Lifecycle;
    37 | declare var afterEach: jest.Lifecycle;
    38 | declare var describe: jest.Describe;

 ERROR(TypeScript)  Subsequent variable declarations must have the same type.  Variable 'afterEach' must be of type 'HookFunction', but here has type 'Lifecycle'.
 FILE  /Users/jun/node_modules/@types/jest/index.d.ts:37:13

    35 | declare var beforeEach: jest.Lifecycle;
    36 | declare var afterAll: jest.Lifecycle;
  > 37 | declare var afterEach: jest.Lifecycle;
       |             ^^^^^^^^^
    38 | declare var describe: jest.Describe;
    39 | declare var fdescribe: jest.Describe;
    40 | declare var xdescribe: jest.Describe;

 ERROR(TypeScript)  Subsequent variable declarations must have the same type.  Variable 'describe' must be of type 'SuiteFunction', but here has type 'Describe'.
 FILE  /Users/jun/node_modules/@types/jest/index.d.ts:38:13

    36 | declare var afterAll: jest.Lifecycle;
    37 | declare var afterEach: jest.Lifecycle;
  > 38 | declare var describe: jest.Describe;
       |             ^^^^^^^^
    39 | declare var fdescribe: jest.Describe;
    40 | declare var xdescribe: jest.Describe;
    41 | declare var it: jest.It;

**Comment by jellydn** [comment]
Thanks @Marchccc Could you try again on the master branch? I have just tried and it works fine for me. Thanks.
