### ISSUE TITLE
[plugin:vite:import-analysis] Failed to resolve import "./artifacts/contracts/MyAwesomeLogo.sol/MyAwesomeLogo.json" from "src/App.tsx". Does the file exist?

### ISSUE THREAD

**Issue by zachchan105** [jellydn/nft-app#422]
Relevant logs:

` [vite] Internal server error: Failed to resolve import "./artifacts/contracts/MyAwesomeLogo.sol/MyAwesomeLogo.json" from "src/App.tsx". Does the file exist?`

` ERROR(TypeScript)  Cannot find module './artifacts/contracts/MyAwesomeLogo.sol/MyAwesomeLogo.json' or its corresponding type declarations.`

**Comment by jellydn** [comment]
Thanks. Let me check.

**Comment by jellydn** [comment]
Thanks @zachchan105 for report. Fixed by https://github.com/jellydn/nft-app/commit/b584e4ef10fa945b5cf83491755e4f219dcd34f5
