### ISSUE TITLE
/api/nft/upload 404

### ISSUE THREAD

**Issue by arrowhitech-gp** [jellydn/nft-app#47]
Hi, 

Thanks for sharing sample project for NFT. I'm trying to deploy it, but i got 404 not found message for /api/nft/upload.
I tried on your demo and it also got the same error.

Could you guide me to fix this error? 

Thank you so much.

**Comment by jellydn** [comment]
Hi @arrowhitech-gp 

Have you added the .env as I mentioned on readme yet? https://github.com/jellydn/nft-app#usage

By the way, I will fix the deployment issue. Thanks.

**Comment by jellydn** [comment]
Here is my setup on local.

.env
```sh
VITE_NFT_DEPLOYED_ADDRESS=0xA0011f0372F6E4E29C0ae6BC64F5C087E48BfEB7
# Create an account on https://nft.storage/ and get a key
NFT_STORAGE_KEY=
VITE_CHAIN_ID=4
API_URL=http://localhost:8080
```
and

server/.env
```sh
# Create an account on https://nft.storage/ and get a key
NFT_STORAGE_KEY=<YOUR NFT STORAGE KEY>
PORT=8080
```

Let me know if that works for you. @arrowhitech-gp

**Comment by jellydn** [comment]
Already fixed the deployment issue. Thank you for your report.

**Comment by arrowhitech-gp** [comment]
Thank @jellydn, I will try and update you soon.

**Comment by arrowhitech-gp** [comment]
It is working fine now, thank you @jellydn
