### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by michaelcodecany** [jellydn/nft-app#785]
### Describe the bug

https://nft-app-demo.productsway.com/

### Reproduction

https://nft-app-demo.productsway.com/

### System Info

```Shell
https://nft-app-demo.productsway.com/
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jellydn** [comment]
Thanks for your report. Fixed by https://github.com/jellydn/nft-app/commit/a0aad9e3937ec4482d7106e2ac037e293a40765b

## ✨ [Demo](https://nft-app.productsway.com/)
