### ISSUE TITLE
error w3name@1.0.4: The engine "node" is incompatible with this module. Expected version ">=16.0.0". Got "14.17.6"

### ISSUE THREAD

**Issue by michaelcodecany** [jellydn/nft-app#787]
### Describe the bug

error w3name@1.0.4: The engine "node" is incompatible with this module. Expected version ">=16.0.0". Got "14.17.6"
error Found incompatible module.

### Reproduction

https://nft-app-demo.productsway.com/

### System Info

```Shell
error w3name@1.0.4: The engine "node" is incompatible with this module. Expected version ">=16.0.0". Got "14.17.6"
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jellydn** [comment]
Hi there,

I guess you haven't used node version management before. There is a https://github.com/jellydn/nft-app/blob/main/.nvmrc file which tell you about what is the node. You could check this out https://github.com/nvm-sh/nvm

This repo only work for node v16. Thanks.

Best regards,
Dung
